Update python-package.yml

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -15,10 +15,10 @@ jobs:
     steps:
     - uses: actions/checkout@v4
 
-    - name: Set up Python ${{ matrix.python-version }}
+    - name: Set up Python
       uses: actions/setup-python@v3
       with:
-        python-version: ${{ matrix.python-version }}
+        python-version: '3.10'
 
     - name: Install dependencies
       run: |
@@ -33,11 +33,12 @@ jobs:
         pip install selenium
         pip install webdriver_manager
 
-    - name: Run Python script
+    - name: Run Python script with retry
       run: |
-        python3 travelrank.py
-      retry:
-        max-attempts: 3  # 최대 3회까지 재시도
+        RETRIES=3
+        for i in $(seq 1 $RETRIES); do
+          python3 travelrank.py && break || echo "Attempt $i failed. Retrying in 10 seconds..." && sleep 10
+        done
 
     - name: Find generated folders
       id: find_folders
